FROM golang:latest AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

ENV GOARCH=amd64
ENV CGO_ENABLED=1
ENV GOOS=linux

RUN go build -o items .

FROM ubuntu
COPY --from=builder /app/items ./items
ENTRYPOINT [ "./items" ]


# FROM golang:latest

# WORKDIR /app

# COPY . .

# CMD ["go", "run", "main.go"]