apiVersion: apps/v1
kind: Deployment
metadata:
  name: fred-items-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fred-items
  template:
    metadata:
      labels:
        app: fred-items
    spec:
      containers:
        - name: fred-items
          image: conorburke/fred-items
---
apiVersion: v1
kind: Service
metadata:
  name: fred-items-srv
spec:
  type: ClusterIP
  selector:
    app: fred-items
  ports:
    - name: fred-items
      protocol: TCP
      port: 3000
      targetPort: 3000